import fs from "node:fs";
import { PDFDocument } from "pdf-lib";
import { loadDocFonts, renderTemplate } from "./src/docTemplate.js";

const body = `
## What we agreed

Federato and Intact walked through the tenant book. The renewal quote holds at the
numbers below, and the two open items are owned and dated.

| Coverage | Limit | Deductible | Premium |
|---|---:|---:|---:|
| Contents | $45,000 | $1,000 | $612 |
| Personal liability | $2,000,000 | $0 | $284 |
| Water damage — sewer backup | $25,000 | $2,500 | $151 |
| Additional living expenses | 24 months | $0 | $88 |
| **Total** | | | **$1,135** |

> Sewer backup is the one line the underwriter flagged: the building is pre-1965 and
> the deductible cannot go below $2,500 without a plumbing inspection on file.

### Why the premium moved

**Winter tires**: confirmed on file, -8% on the auto side of the bundle
**Claims history**: one not-at-fault in 2023, no rating impact
**Bundle**: auto + tenant together, -12% applied to both policies

1. Underwriting accepted the 2023 claim as not-at-fault, so the surcharge came off.
2. The bundle discount replaced the standalone tenant rate.
3. The water sub-limit went up from $15,000 to $25,000 at no extra cost.

### Action items

- [x] Pull the 2023 claim file and confirm not-at-fault — Dana, done Sep 17
- [ ] Book the plumbing inspection before binding — Marcus, by Sep 26
- [ ] Send the signed application back — client, by Oct 1
  - the e-sign link expires after 14 days
  - a wet signature is fine if the portal gives them trouble

### Rate comparison

| Carrier | Annual | vs Intact | Notes |
|---|---:|---:|---|
| Intact (recommended) | $1,135 | — | bundle applied, water at $25k |
| Aviva | $1,268 | +11.7% | water capped at $15k |
| Wawanesa | $1,204 | +6.1% | no bundle available on tenant |
| Economical | $1,391 | +22.6% | declined water endorsement |

---

Anything not listed here was not discussed. Quote is valid for 30 days from the date
above and assumes the inspection clears. Full policy wording is in the carrier's
\`IPB-2024-TEN\` form, and the portal link is [the Intact broker portal](https://portal.example.com/quotes/IPB-2024-TEN).

\`\`\`
policy   IPB-2024-TEN
effective 2026-10-01
broker    D. Okonkwo  #48812
\`\`\`
`;

const doc = await PDFDocument.create();
const fonts = await loadDocFonts(doc);
console.log("geist embedded:", fonts.geist);
const pages = renderTemplate(doc, fonts, {
  title: "Tenant renewal — quote, rationale and next steps",
  subtitle: "Intact Insurance · renewal call with Marcus Reyes · 19 September 2026",
  figures: [
    { label: "Annual premium", value: "$1,135", note: "12-month term, bundled" },
    { label: "Saved vs. last year", value: "-14.2%", note: "was $1,323" },
    { label: "Binds by", value: "2026-10-01", note: "inspection must clear" },
  ],
  body,
  footer: "Tenant renewal — generated by plus1 from the 19 Sep call",
});
const bytes = await doc.save();
fs.writeFileSync("/tmp/doc-review/sample.pdf", bytes);
console.log("pages:", pages, "bytes:", bytes.length);
