// Bundles src/page into one IIFE and writes it both as dist/page.iife.js and
// as a TS module (src/page-bundle.generated.ts) so the Node side can inline it
// into Playwright's addInitScript. Meet's CSP blocks remote scripts, so the
// bundle must travel inside the init script itself.
import { build } from "esbuild";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const common = {
  bundle: true,
  format: "iife",
  platform: "browser",
  target: ["chrome120"],
  minify: true,
  sourcemap: false,
  legalComments: "none",
  define: { "process.env.NODE_ENV": '"production"' },
  write: false,
  logLevel: "warning",
};
const [page, early] = await Promise.all([
  build({ ...common, entryPoints: [resolve(root, "src/page/index.ts")] }),
  build({ ...common, entryPoints: [resolve(root, "src/page/early.ts")] }),
]);
const code = page.outputFiles[0].text;
const earlyCode = early.outputFiles[0].text;
mkdirSync(resolve(root, "dist"), { recursive: true });
writeFileSync(resolve(root, "dist/page.iife.js"), code);
writeFileSync(resolve(root, "dist/early.iife.js"), earlyCode);
writeFileSync(
  resolve(root, "src/page-bundle.generated.ts"),
  `// GENERATED by scripts/build-page.mjs — do not edit.\n` +
    `/** The in-page avatar bridge (livekit-client included) as a single IIFE string. Inject AFTER the page loads. */\n` +
    `export const PAGE_BUNDLE: string = ${JSON.stringify(code)};\n` +
    `/** The tiny getUserMedia override. The only thing that runs before the page's own JS (addInitScript). */\n` +
    `export const EARLY_BUNDLE: string = ${JSON.stringify(earlyCode)};\n`,
);
console.log(`page bundle: ${(code.length / 1024).toFixed(0)} KiB · early bundle: ${(earlyCode.length / 1024).toFixed(1)} KiB`);
